--스프링 부트가 지원하는 기본 SQL 스크랩트를 사용한 DB 초기화 기능--
drop table if exists item CASCADE;
create table item
(
    id          bigint generated by default as identity,
    item_name   varchar(10),
    price       integer,
    quantity    integer,
    primary key (id)
);